export * from "./components/navbar/navBar"
export * from "./components/section-home/sectionHome"
export * from "./components/section-products/sectionProducts"
export * from "./components/image/image"
export * from "./components/section-service/sectionService"
export * from "./components/about-me/aboutMe"
export * from "./components/footer/footer"